/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jtext.app;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class MessageUtilsTest {
  @Test
  void testGetMessage() {
    assertEquals("Hello Cat!", Utility.replaceWords("World", "Cat", "Hello World!"));
  }
}
